apiVersion: v1
kind: Service
metadata: 
  name: fe-service
  labels:
    type: fe
spec:
  # type: ClusterIP
  type: NodePort
  ports:
    - nodePort: 30004
      port: 80
      targetPort: 80
  selector:
    type: fe
