name: VOTEAPP-BUILD-CICD
run-name: ${{ github.actor }} has triggered the workflow.
on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build.yaml"
      - "voteapp-api-go/**"
      - "voteapp-db-mongo/**"
      - "voteapp-frontend-react/**"
jobs:
  build-frontend-react:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: voteapp-frontend-react
    steps:
      - name: Perform checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build the Image and Push to GHCR
        run: |
          docker build . -t ghcr.io/${{ secrets.GHCR_USERNAME }}/voteapp-fe:${{ github.sha }};
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/voteapp-fe:${{ github.sha }}

  build-api-go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: voteapp-api-go
    steps:
      - name: Perform checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build the Image and Push to GHCR
        run: |
          docker build . -t ghcr.io/${{ secrets.GHCR_USERNAME }}/voteapp-be:${{ github.sha }};
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/voteapp-be:${{ github.sha }}

  build-db-mongo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: voteapp-db-mongo
    steps:
      - name: Perform checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build the Image and Push to GHCR
        run: |
          docker build . -f db-image.Dockerfile -t ghcr.io/${{ secrets.GHCR_USERNAME }}/voteapp-db:${{ github.sha }};
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/voteapp-db:${{ github.sha }}
