name: VOTEAPP-DEPLOY-CICD
run-name: ${{ github.actor }} has triggered the workflow.
on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/deployment.yaml"
      - "kubernetes-files/**"
  workflow_run:
    workflows: 
      - "VOTEAPP-BUILD-CICD"
    types:
      - "completed"
jobs:
  deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kubernetes-files
    steps:
      - name: Perform checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.EKS_CLUSTER_REGION }}

      - name: Connect to the EKS Cluster
        run: aws eks update-kubeconfig --region ${{ secrets.EKS_CLUSTER_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      # - name: Execute this run for only 1st time.
      #   run: |
      #     kubectl apply -f db-deploy.yml;
      #     kubectl apply -f api-deployment.yml;
      #     kubectl apply -f fe-deployment.yml
      
      - name: Execute this run after the 1st time.
        run: |
          kubectl set image deployment/fe-deployment fe-container=ghcr.io/${{ secrets.GHCR_USERNAME }}/voteapp-fe:${{ github.sha }};
          kubectl set image deployment/api-deployment api-container=ghcr.io/${{ secrets.GHCR_USERNAME }}/voteapp-be:${{ github.sha }};
          kubectl set image statefulset/mongo mongodb=ghcr.io/${{ secrets.GHCR_USERNAME }}/voteapp-db:${{ github.sha }}

      - name: Run the Services
        run: |
          kubectl apply -f api-service.yml;
          kubectl apply -f fe-service.yml

      # - name: Run the Ingress files
      #   run: kubectl apply -f ingress-resource.yml
